# Site settings
title: Eugen Istoc
email: eugenistoc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Full-time software engineer, open source advocate, lay theologian,
  part-time soccer and fitness enthusiast and full-time Christian.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eugenistoc.com" # the base hostname & protocol for your site
twitter_username: eugenistoc
github_username:  genu
linkedin_profile_url: https://www.linkedin.com/in/eugen-istoc-4a4932b

# Build settings
markdown: kramdown
